name: Build project

on:
  push:
    branches: [ "main" ]
    tags:        
      - '*'           #

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: dart-lang/setup-dart@v1
    - name: Install sass
      run: dart pub global activate sass
    - name: Run makefile
      run: make 
    - name: save artefact
      uses: actions/upload-artifact@v4
      with:
        name: cleanpurple.css
        path: dist/cleanpurple.css

  publish:
    needs: build
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cleanpurple.css
      - uses: "ncipollo/release-action@v1"
        with:
          name: cleanpurple.css
          artifacts: cleanpurple.css
          allowUpdates: true

