name: Build project

on:
  push:
    branches: [ "main" ]
    tags:        
      - '*'           #

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: dart-lang/setup-dart@v1
    - name: Install sass
      run: dart pub global activate sass
    - name: Run makefile
      run: make 
    - name: save artefact
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: dist/cleanpurple.css

  publish:
    needs: build
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: output
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          name: "${GITHUB_REF#refs/tags/}"
          prerelease: false
          files: dist/cleanpurple.css
